### ISSUE TITLE
Use the actions drop down on details pages

### ISSUE THREAD

**Issue by george-haeger** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#125]
We should use the drop down action concept on the details pages like we do on the listings pages. An example is on the Products page we are using the action dropdown to show all the actionable items in a clean dropdown. If we are going to do that on the listings pages I think we should do the same on the product details, promotion details, order details, etc...

If this is a design thing to do it different we can close this ticket. We can discuss at our next meeting. 
@robertsoniv

**Comment by abishop451** [comment]
This Issue was created to adding Actions to the Product Detail page: https://github.com/Sitecore/Sitecore.Commerce.Headstart.ReactAdmin/issues/150

Use the existing patterns to add the Actions menu to the Promotions and Order Details pages as well
1. On Order Details, add an Actions menu and put "Export to CSV", "Export to PDF", and "Print Shipping Label" as options in the Actions Menu.
2. On Promotion Details, add an Actions menu and put "Delete Promotion" as an option in the menu.

**Comment by crhistianramirez** [comment]
Complete
