### ISSUE TITLE
Allow Supplier User to login to React Admin

### ISSUE THREAD

**Issue by abishop451** [Sitecore/Sitecore.Commerce.Headstart.ReactAdmin#154]
Update configuration to allow a Supplier User to login to the React Admin login page using Supplier credentials.  User will need proper roles and permissions to accomplish this.

**Comment by crhistianramirez** [comment]
This is possible now. You can log in with `supplier01` (same password as for admin)

I did find a bug however that `ProductManager` role group is missing `ProductFacetReader` so you will get errors when trying to view the detail page. I opened up a PR to resolve the issue. This isn't a problem for admins because they inherit `ProductFacetAdmin` from the `SettingsManager` role group (which suppliers won't have access to)

**Comment by crhistianramirez** [comment]
Merged into development
